### ISSUE TITLE
Error accessing pyshopee in Python 2.7.12

### ISSUE THREAD

**Issue by ppts-odoo** [JimCurryWang/python-shopee#26]
I have installed pyshopee in my machine. It has installed successfully without any error.
While import the pyshopee, Im getting below error.

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshopee
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyshopee/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/pyshopee/client.py", line 40
    class Client(object, metaclass=ClientMeta):
                                  ^
SyntaxError: invalid syntax
>>>

**Comment by JimCurryWang** [comment]
Hi @ppts-odoo ,

Pyshopee can only be run on Python3 right now, however, I am willing to receive any PR for the Python2 version. 

Thanks
